# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=250)),
                ('shape', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reported_at', models.DateField(blank=True, null=True)),
                ('occurred_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
