# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_search_vector'),
    ]

    operations = [
        migrations.RunSQL("""
        CREATE TRIGGER tsvectorupdate BEFORE INSERT OR UPDATE
        ON reports_report FOR EACH ROW EXECUTE PROCEDURE
        tsvector_update_trigger(
            search_vector,
            'pg_catalog.english',
            location, shape, description);

        UPDATE reports_report SET location=location;
        """,
        "DROP TRIGGER tsvectorupdate ON reports_report;")
    ]
