version: '2'

services:
  db:
    image: postgres

  nginx:
    image: nginx:latest
    expose:
      - "8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
