export const FETCH_SIGHTINGS_REQUEST = "FETCH_SIGHTINGS_REQUEST";
export const FETCH_SIGHTINGS_PAGE_REQUEST = "FETCH_SIGHTINGS_PAGE_REQUEST";
export const FETCH_SIGHTINGS_SUCCESS = "FETCH_SIGHTINGS_SUCCESS";
export const FETCH_SIGHTINGS_FAILURE = "FETCH_SIGHTINGS_FAILURE";

export const FETCH_SIGHTING_REQUEST = "FETCH_SIGHTING_REQUEST";
export const FETCH_SIGHTING_SUCCESS = "FETCH_SIGHTING_SUCCESS";
export const FETCH_SIGHTING_FAILURE = "FETCH_SIGHTING_FAILURE";
