"""Remove precision from lat/lng fields

Revision ID: 2a65c28d98e5
Revises: 898889eea223
Create Date: 2018-04-08 08:37:32.116724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a65c28d98e5"
down_revision = "898889eea223"
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column("reports", "latitude", type_=sa.Numeric(precision=None))
    op.alter_column("reports", "longitude", type_=sa.Numeric(precision=None))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reports", "latitude", type_=sa.Numeric(precision=2))
    op.alter_column("reports", "longitude", type_=sa.Numeric(precision=2))


# ### end Alembic commands ###
